name: Build Check

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ./theia-ai-exerciser
        run: yarn install

      - name: Build Theia AI Exerciser
        working-directory: ./theia-ai-exerciser
        run: yarn build
